baseURL = 'https://dekuso.github.io/dekusosblog/'
languageCode = 'de'
defaultContentLang = "de-de"
title = "dekuso's blog"
theme = "archie"
copyright = "© dekuso"

[params]
  dateFormat = "02.01.2006"
  mode="light" # color-mode → light,dark,toggle or auto
  useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
  mathjax = false # enable MathJax support
  katex = false # enable KaTeX support  

            
# Main menu Items

[[menu.main]]
name = "alle posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "über mich"
url = "/about"
weight = 3